Update GAS version and reformat reference cluster file.
phac-nml/gasnomenclature pull request #31
Opened 2024-10-24 17:57 UTC by kylacochrane

THIS IS A WORK IN PROGRESS.

Some of the tests are failing.

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [x] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2024-11-21 19:12 UTC, kylacochrane commented
Once a new version of `GAS` is released, the container directive will need to be updated in the `gas/call` module. The tests should run as expected and pass CI testing unless there are also changes in the `buildNewick` function in `GAS`. In which case the [expected_tree.nwk](https://github.com/phac-nml/gasnomenclature/blob/main/tests/data/clusters/expected_tree.nwk) file in the `test/data/clusters` file will also need to be updated.

2025-01-06 19:55 UTC, sgsutcliffe commented
Updated the GAS version which fixed the attribute error in the tests but some other errors have poped up:
- 'Test pipeline with single threshold set to 1'
- 'Test pipeline with threshold set to 1,0'
- 'Full pipeline hashes and missing data'
- 'Full pipeline hashes and missing data count missing as differences'
- 'Full pipeline remove loci with missing data'

2025-01-06 20:02 UTC, sgsutcliffe commented
For 'Test pipeline with single threshold set to 1' and 'Test pipeline with threshold set to 1,0' the address for sampleQ the is 2 and 2.2 respectively. So I updated the `called/expected_results*` the `*_iridanext.output.json` files to reflect this. I do this with caution because, based on my understanding the original expected results were correct, and tests are right to fail.

2025-01-06 20:20 UTC, sgsutcliffe commented
The subsequent tests also had the same issue. Will need to explore as to whether it is the address that was originally wrong or if there is an issue with GAS 0.1.3 https://github.com/phac-nml/gasnomenclature/pull/31/commits/26ce6ffcbe529fb8d810c7802f0321c11525518b

2025-01-07 19:05 UTC, apetkau requested changes
Thanks so much Steven. This looks great 😄 

And thanks so much @kylacochrane for all your work on this too 😄 

I haven't finished reviewing, but sending this PR early since I had one comment.

2025-01-08 19:53 UTC, apetkau approved these changes
Thanks so much for making that change Steven. Everything else looks great 😄

2025-01-08 20:51 UTC, merged