Workflow
phac-nml/gasnomenclature pull request #4
Opened 2024-04-02 21:25 UTC by mattheww95

2024-04-03 14:43 UTC, mattheww95 commented
Linting tests are failing as I did not update the schema. I wanted prioritize getting the main "bones" of the pipeline in with test data so that critical feedback can be provided on the structure of the pipeline itself to make sure it fits what is expected.

2024-04-03 15:06 UTC, emarinier commented on workflows/gas_nomenclature.nf
> +        exit 1, "${params.pd_mapping_file}: Does not exist but was passed to the pipeline. Exiting now."
Do you know if these are the accepted way of exiting from nextflow, or should we use `error()`?

2024-04-03 15:06 UTC, emarinier requested changes
I think the changes here look good overall. I have some general comments:

- It might be worth adding failure / error testing.
- Generally, I'd advise against merging any TODOs into a dev / main branch, and instead do the TODO or make an issue on GitHub to do it later.
- I assume we're going forward with default parameters all listed in the `nextflow.config`?

2024-04-03 15:07 UTC, emarinier commented
Oh, also getting the tests to pass.

2024-04-03 16:22 UTC, mattheww95 commented
Good news all tests passed! 

I am not proud of it, but to resolve the TODO I changed it to a point for discussion.

As for the defualt parameters, I dont know how most of the parameters to be passed to the tools are meant to be used so I just left them there for now.

I can add failure testing as well! I just thought it would be better to leave that as a seperate PR, I just wanted to get the initial skeleton of the tests implemented and full disclosure I was going to bug you about those afterwards...

2024-04-04 14:40 UTC, emarinier approved these changes

2024-04-04 20:15 UTC, merged