Check to ensure sample IDs match MLST.JSON keys
phac-nml/gasnomenclature pull request #9
Opened 2024-05-08 22:02 UTC by kylacochrane

Added the ability to check that the sample IDs from the samplesheet (`meta.id`) matches the corresponding JSON key from the mlst.json file (also included in the samplesheet as `mlst_alleles`)

- the module will output an `error_report.csv` only for the samples where the ID ≠ Key
- the module also uses `val(meta)` as an input (from samplesheet) to ensure that the `meta.ids` are stored in the pipeline, enabling nf-iridanext plugin functionality

TODO:
- tests still need to be added 
- enhancement: update workflow to remove samples from pipeline if [ID ≠ Key]

2024-05-16 17:00 UTC, apetkau requested changes
This is amazing. Thanks so much @kylacochrane 😄 .

In addition to what we talked about I had a few other comments.

2024-05-16 19:28 UTC, kylacochrane commented on workflows/gas_nomenclature.nf
> +        def id_match = file.text.trim()
I am actually quite surprised it did work. Although I have made a note that we may want to switch to a Groovy code in the future to update the `meta` object instead 🤔

2024-05-16 20:43 UTC, kylacochrane commented on modules/local/filter_query/main.nf
> +        --out-file ${outputFile}.tmp
Oh yes! Sure thing: [6cf40c3](https://github.com/phac-nml/gasnomenclature/pull/9/commits/6cf40c30d6aed50d13cb8c151cd94ec5236f8ecc)

2024-05-16 20:43 UTC, kylacochrane commented on modules/local/filter_query/main.nf
> +    csvtk cut -f 1,2 ${outputFile}.tmp > ${outputFile}.${out_extension}
indeed 😄 [6cf40c3](https://github.com/phac-nml/gasnomenclature/pull/9/commits/6cf40c30d6aed50d13cb8c151cd94ec5236f8ecc)

2024-05-16 20:46 UTC, kylacochrane commented on bin/check_samplesheet.py
> -            logger.critical(f"The sample sheet **must** contain these column headers: {req_cols}.")
Removed here: [5bfe569](https://github.com/phac-nml/gasnomenclature/pull/9/commits/5bfe569ec975ee4b38dc91adec005541f9f314a4)

2024-05-16 21:29 UTC, kylacochrane commented on bin/error_report.py
> +    json_data = json.load(open(json_file))
Done here: [cf37bfe](https://github.com/phac-nml/gasnomenclature/pull/9/commits/cf37bfea9b84bb97ae5df045aee57ff98a3f8d91)

2024-05-17 15:19 UTC, kylacochrane commented
**Additional changes:**
Combined INPUT_CHECK and ERROR_REPORT into a single process: [cf37bfe](https://github.com/phac-nml/gasnomenclature/pull/9/commits/cf37bfea9b84bb97ae5df045aee57ff98a3f8d91)
Filtered out samples using Groovy logic in workflow (instead of a separate process): [5456aa7](https://github.com/phac-nml/gasnomenclature/pull/9/commits/5456aa7050dbb7d71387f7a70d2da302b9f5635f)

2024-05-17 19:35 UTC, apetkau commented on workflows/gas_nomenclature.nf
> +        def id_match = file.text.trim()
Thanks so much for testing this out. I'm glad it does work 😄

2024-05-17 20:05 UTC, apetkau requested changes
This looks great. Thanks so much for your work @kylacochrane 😄 . Just one small comment.

2024-05-21 13:39 UTC, kylacochrane commented on modules/nf-core/custom/dumpsoftwareversions/templates/dumpsoftwareversions.py
> +        versions_by_process = (
Reverted in: [4589456](https://github.com/phac-nml/gasnomenclature/pull/9/commits/4589456a2cc7117adf54b95831a80925bd653d11)

2024-05-21 14:01 UTC, kylacochrane commented on workflows/gas_nomenclature.nf
> +        [meta + [id_match: id_match], json]
Done here: [9748287](https://github.com/phac-nml/gasnomenclature/pull/9/commits/97482872ab05664a0235709aa7962ee8e658edb2)

2024-05-22 16:46 UTC, apetkau approved these changes
This looks great. Thanks so much for all your hard work on this @kylacochrane 😄

2024-05-22 16:46 UTC, apetkau commented on tests/data/samplesheets/samplesheet_test1.csv
> +sample2,https://raw.githubusercontent.com/phac-nml/gasnomenclature/add_tests/tests/data/reports/sample7.mlst.json,1.1.1
As a note, once this PR is merged you'll have to update the URL here to point to `dev`. You can just directly commit that to the `dev` branch.

2024-05-22 17:02 UTC, merged